#!/usr/bin/env python3
"""Generate a C/C++ source pair from a binary blob.

Emits <name>.cpp defining `extern "C" const unsigned char <symbol>[]` plus an
optional `<symbol>_len` int, and a matching C-compatible declaration header.
Used by src/data/meson.build to build the embedded data blobs (initcart, logo,
font) from their .bin payloads instead of checked-in C string-literal files.
The header stays consumable from both C and C++ translation units; byte
arrays and ints have identical layout across the language boundary.
"""

from __future__ import annotations

import argparse
import os
import sys

GUARD_INNER = "GENERATOR_{}_DATA_H"


def c_hex_literal(data: bytes) -> str:
    lines = []
    for off in range(0, len(data), 16):
        chunk = data[off : off + 16]
        lines.append("  " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def write_header(path: str, symbol: str, length_symbol: str | None) -> None:
    guard = GUARD_INNER.format(symbol.upper())
    lines = [
        "/* Generated by scripts/bin2c_source.py - do not edit. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    if length_symbol:
        lines.append(f"extern const int {length_symbol};")
        lines.append("")
    lines.append(f"extern const unsigned char {symbol}[];")
    lines += [
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def write_source(
    path: str,
    blob_name: str,
    symbol: str,
    data: bytes,
    length_symbol: str | None,
    header_name: str,
) -> None:
    lines = [
        "/* Generated by scripts/bin2c_source.py from "
        f"{blob_name} - do not edit. */",
        f'#include "{header_name}"',
        "",
    ]
    if length_symbol:
        lines.append(f'extern "C" const int {length_symbol} = {len(data)};')
        lines.append("")
    lines.append(f'extern "C" const unsigned char {symbol}[] = {{')
    lines.append(c_hex_literal(data))
    lines += ["};", ""]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", help="binary payload file")
    parser.add_argument("--symbol", required=True, help="C symbol for the array")
    parser.add_argument("--source", required=True, help="output .cpp path")
    parser.add_argument("--header", required=True, help="output .h path")
    parser.add_argument(
        "--length-symbol",
        default=None,
        help="also define <symbol> with the payload byte count",
    )
    args = parser.parse_args()

    with open(args.input, "rb") as f:
        data = f.read()
    if not data:
        print(f"error: empty payload {args.input}", file=sys.stderr)
        return 1

    write_header(args.header, args.symbol, args.length_symbol)
    write_source(
        args.source,
        args.input,
        args.symbol,
        data,
        args.length_symbol,
        os.path.basename(args.header),
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
